version: "3.9"

services:
  pf_orchard_localization:
    build:
      context: ..
      dockerfile: docker/Dockerfile.desktop-contained
    volumes:
      - ../:/home/vscode/pf_orchard_localization:rw
      - /media/jostan/portabits/pf_app_data:/home/vscode/app_data:rw
    network_mode: "host"
    runtime: nvidia   
    ipc: "host"
    user: vscode
    command: ["python3", "/home/vscode/pf_orchard_localization/scripts/run_pf_bag_app.py"]

