# ----------------------
# General parameters
# ----------------------
#image_save_dir: /media/jostan/portabits/map_making_data/cherry_orchard/training_images/training_images_test/
image_save_dir: /home/jostan/Documents/save_test1/
initial_data_time: 0  # seconds into the bag file
initial_data_file_index: 0  # index of the bag file

image_display_scale: 1.0

# ----------------------
# Bi-axe orchard
# ----------------------
# width_estimation_config_file_path: /home/jostan/OneDrive/Docs/Grad_school/Research/code_projects/width_estimation/config/width_estimation_bi-axe_config.yaml

# data_file_dir: /media/jostan/portabits/bags_new/bi-axe_orchard/row_1/

# rgb_topic: /camera/color/image_raw
# depth_topic: /camera/aligned_depth_to_color/image_raw
# odom_topic: /odometry/filtered


# ----------------------
# Cherry orchard
# ----------------------
# width_estimation_config_file_path: /home/jostan/OneDrive/Docs/Grad_school/Research/code_projects/width_estimation/config/width_estimation_cherry_config.yaml

# data_file_dir: /media/jostan/portabits/bags_new/cherry_orchard/row_3/

# rgb_topic: /camera/color/image_raw
# depth_topic: /camera/aligned_depth_to_color/image_raw
# odom_topic: /odometry/filtered

# ----------------------
# Jazz apple orchard
# ----------------------
width_estimation_config_file_path: /home/jostan/OneDrive/Docs/Grad_school/Research/code_projects/width_estimation/config/width_estimation_jazz_config.yaml
pf_config_file_path: /home/jostan/OneDrive/Docs/Grad_school/Research/code_projects/pf_orchard_localization/config/parameters_pf.yaml

map_data_path: /home/jostan/OneDrive/Docs/Grad_school/Research/code_projects/orchard_map_maker/scripts/map_making1/map_data_main.json

#data_file_dir: /media/jostan/MOAD/research_data/apple_orchard_data/2023_orchard_data/uncompressed/synced/pcl_mod/
data_file_dir: /media/jostan/portabits/pcl_mod/

rgb_topic: /registered/rgb/image
depth_topic: /registered/depth/image
odom_topic: /odometry/filtered


