# ----------------------
# General parameters
# ----------------------
image_save_dir: /home/vscode/app_data/image_save_dir
initial_data_time: 0  # seconds into the bag file
initial_data_file_index: 0  # index of the bag file

image_display_scale: 1.0


# ----------------------
# Jazz apple orchard
# ----------------------
pf_config_file_path: /home/vscode/pf_orchard_localization/config/parameters_pf.yaml

map_data_path: /home/vscode/app_data/map_data_jazz_new.json

data_file_dir: /home/vscode/app_data/test_bags/

rgb_topic: /registered/rgb/image
depth_topic: /registered/depth/image

odom_topic: /odometry/filtered

image_fps: 10