# ----------------------
# General parameters
# ----------------------

image_display_scale: 1.0


# ----------------------
# Jazz apple orchard
# ----------------------

map_data_path: /home/vscode/app_data/map_data_jazz_new.json

# rgb_topic: /throttled/registered/rgb/image
# depth_topic: /throttled/registered/depth/image

pf_config_file_path: /home/vscode/pf_orchard_localization/config/parameters_pf.yaml

